### ISSUE TITLE
请问有人可以提供编译好的版本吗？

### ISSUE THREAD

**Issue by SafeCryptex** [shizhuolin/PyCTP#15]
首先感谢原创作者shizhuolin！其次不是专业搞编程的，要构建环境太麻烦了，如果有人能提供编译好的版本就好了。如果有人能提供，我在这里预先表示感谢！

**Comment by Hilyme** [comment]
同求编译好的版本，
 新的适应穿透式的，我这儿编译完也是不能用， 会报ImportError: DLL load failed: 找不到指定的模块。 
 以前版本的就可以使用，  感觉是我编译出来的文件有问题， 但是编译时也没有报错

**Comment by hanmin72** [comment]
编译通过，也能执行test_CTP.py但是好像没有ReqAuthenticate方法，也没地方配置Authcode和APPID啊。

**Comment by SafeCryptex** [comment]
> 编译通过，也能执行test_CTP.py但是好像没有ReqAuthenticate方法，也没地方配置Authcode和APPID啊。


请问你的linux编译问题是怎么解决的？因为windows安装vs非常麻烦，我在linux编译 的时候也碰到了找不到 -lWinDataCollect的错误，请问你是怎么解决的？

**Comment by hanmin72** [comment]
linux版本还没解决，先找了win10的测试

**Comment by SafeCryptex** [comment]
> linux版本还没解决，先找了win10的测试


应该是需要在Login之前先验证客户端，仿着Login写一个类似def Authenticate(self, AppID, BrokerID, UserID, AuthCode)的函数，具体编译我还没有搞定，所以也不清楚怎么实施。请问你方便找一个网盘共享一下你编译好的版本吗？谢谢了。

**Comment by hanmin72** [comment]
链接：https://pan.baidu.com/s/1cw5lwMXIeel2LR3D9w-wFQ 
提取码：l9sa

**Comment by SafeCryptex** [comment]
> 链接：https://pan.baidu.com/s/1cw5lwMXIeel2LR3D9w-wFQ
> 提取码：l9sa

谢谢

**Comment by hanmin72** [comment]
> > 链接：https://pan.baidu.com/s/1cw5lwMXIeel2LR3D9w-wFQ
> > 提取码：l9sa
> 
> 谢谢

Ubuntu编译已经搞定了，修改setup.py

if platform.system() == 'Linux':
    optional['extra_compile_args'] = ['-std=c++11']
    optional['runtime_library_dirs'] = ['./']
    optional['include_dirs']=['./v6.3.15_20190220_api_clientdatacollectdll_linux64']
    optional['library_dirs']=['./v6.3.15_20190220_api_tradeapi_se_linux64']
#    depend_dynamics = ['libthostmduserapi.so', 'libthosttraderapi.so']
if platform.system() == 'Windows':
    optional['include_dirs'] = ['./v6.3.6_20160606_tradeapi_windows']
    optional['library_dirs'] = ['./v6.3.6_20160606_tradeapi_windows']
    if '64 bit' in platform.python_compiler():
        optional['include_dirs'] = ['./v6.3.15_20190220_tradeapi64_se_windows','v6.3.15_20190220_clientdll64_windows']
        optional['library_dirs'] = ['./v6.3.15_20190220_tradeapi64_se_windows','v6.3.15_20190220_clientdll64_windows']
#    depend_dynamics = ['thostmduserapi.dll', 'thosttraderapi.dll']
argments = dict(name='PyCTP',
                sources=sources,
                language='c++',
                libraries=['thostmduserapi_se', 'thosttraderapi_se','LinuxDataCollect'],
                depends=depends)

即可成功编译，不过认证申请发出后，CTP提示认证失败 63这个还没搞定咋回事

**Comment by SafeCryptex** [comment]
> > > 链接：https://pan.baidu.com/s/1cw5lwMXIeel2LR3D9w-wFQ
> > > 提取码：l9sa
> > 
> > 
> > 谢谢
> 
> Ubuntu编译已经搞定了，修改setup.py
> 
> if platform.system() == 'Linux':
> optional['extra_compile_args'] = ['-std=c++11']
> optional['runtime_library_dirs'] = ['./']
> optional['include_dirs']=['./v6.3.15_20190220_api_clientdatacollectdll_linux64']
> optional['library_dirs']=['./v6.3.15_20190220_api_tradeapi_se_linux64']
> 
> # depend_dynamics = ['libthostmduserapi.so', 'libthosttraderapi.so']
> if platform.system() == 'Windows':
> optional['include_dirs'] = ['./v6.3.6_20160606_tradeapi_windows']
> optional['library_dirs'] = ['./v6.3.6_20160606_tradeapi_windows']
> if '64 bit' in platform.python_compiler():
> optional['include_dirs'] = ['./v6.3.15_20190220_tradeapi64_se_windows','v6.3.15_20190220_clientdll64_windows']
> optional['library_dirs'] = ['./v6.3.15_20190220_tradeapi64_se_windows','v6.3.15_20190220_clientdll64_windows']
> 
> # depend_dynamics = ['thostmduserapi.dll', 'thosttraderapi.dll']
> argments = dict(name='PyCTP',
> sources=sources,
> language='c++',
> libraries=['thostmduserapi_se', 'thosttraderapi_se','LinuxDataCollect'],
> depends=depends)
> 
> 即可成功编译，不过认证申请发出后，CTP提示认证失败 63这个还没搞定咋回事

good job! 你把认证过程的代码贴一下，大家分析一下。

**Comment by hanmin72** [comment]
和期货公司沟通了下，说是要用模拟账号进行仿真测试，难怪我用正式账号会报认证错误，继续等模拟账号下来再试

**Comment by SafeCryptex** [comment]
> 和期货公司沟通了下，说是要用模拟账号进行仿真测试，难怪我用正式账号会报认证错误，继续等模拟账号下来再试

好的。如果方便的话麻烦把认证的代码也共享一下，这样我们其他人就不用再动脑了，哈哈。。

**Comment by hanmin72** [comment]
> > 和期货公司沟通了下，说是要用模拟账号进行仿真测试，难怪我用正式账号会报认证错误，继续等模拟账号下来再试
> 
> 好的。如果方便的话麻烦把认证的代码也共享一下，这样我们其他人就不用再动脑了，哈哈。。

等我测试通过后发上来

**Comment by SafeCryptex** [comment]
> > > 和期货公司沟通了下，说是要用模拟账号进行仿真测试，难怪我用正式账号会报认证错误，继续等模拟账号下来再试
> > 
> > 
> > 好的。如果方便的话麻烦把认证的代码也共享一下，这样我们其他人就不用再动脑了，哈哈。。
> 
> 等我测试通过后发上来

感谢！我用vnpy测试simnow账号也是63错误。

**Comment by hanmin72** [comment]
> 同求编译好的版本，
> 新的适应穿透式的，我这儿编译完也是不能用， 会报ImportError: DLL load failed: 找不到指定的模块。
> 以前版本的就可以使用， 感觉是我编译出来的文件有问题， 但是编译时也没有报错

复制库文件到build/scripts-3.6就能解决

**Comment by Hilyme** [comment]
import PyCTP
ImportError: DLL load failed: 找不到指定的模块。
还是这个问题， 请问有什么解决方法吗？

**Comment by SafeCryptex** [comment]
> import PyCTP
> ImportError: DLL load failed: 找不到指定的模块。
> 还是这个问题， 请问有什么解决方法吗？
把所依赖的dll和pyd文件都复制到同一个目录下了吗？

**Comment by hanmin72** [comment]
> import PyCTP
> ImportError: DLL load failed: 找不到指定的模块。
> 还是这个问题， 请问有什么解决方法吗？
先用python setup.py build编译，完成后，执行python setup.py install.然后复制v6.3.15_20190220_tradeapi64_se_windows和v6.3.15_20190220_clientdll64_windows目录里面的文件到scripts目录下
就可以正常执行了

**Comment by Hilyme** [comment]
> > import PyCTP
> > ImportError: DLL load failed: 找不到指定的模块。
> > 还是这个问题， 请问有什么解决方法吗？
> > 先用python setup.py build编译，完成后，执行python setup.py install.然后复制v6.3.15_20190220_tradeapi64_se_windows和v6.3.15_20190220_clientdll64_windows目录里面的文件到scripts目录下
> > 就可以正常执行了



> > import PyCTP
> > ImportError: DLL load failed: 找不到指定的模块。
> > 还是这个问题， 请问有什么解决方法吗？
> > 把所依赖的dll和pyd文件都复制到同一个目录下了吗？

复制到同一个目录下了  现在script目录下一共四个文件   不过PyCTP.pyd文件我是从PyCTP.cp35-win_amd64.pyd  这个重命名过去的。  还有执行python setup.py build 的时候没有报错只报了一个warning--- PyCTP.obj : warning LNK4197: 多次指定导出“PyInit_PyCTP”；使用第一个规范，    不知道是否有影响

**Comment by Hilyme** [comment]
找到问题了， 是我编译完没有把DataCollect.h、WinDataCollect.dll、WinDataCollect.lib这三个文件也放到scripts下。。。。。。。。。。

**Comment by hanmin72** [comment]
> > > > 和期货公司沟通了下，说是要用模拟账号进行仿真测试，难怪我用正式账号会报认证错误，继续等模拟账号下来再试
> > > 
> > > 
> > > 好的。如果方便的话麻烦把认证的代码也共享一下，这样我们其他人就不用再动脑了，哈哈。。
> > 
> > 
> > 等我测试通过后发上来
> 
> 感谢！我用vnpy测试simnow账号也是63错误。

仿真环境客户端验证通过了，下一步可以申请真实环境了

**Comment by SafeCryptex** [comment]
> > > > > 和期货公司沟通了下，说是要用模拟账号进行仿真测试，难怪我用正式账号会报认证错误，继续等模拟账号下来再试
> > > > 
> > > > 
> > > > 好的。如果方便的话麻烦把认证的代码也共享一下，这样我们其他人就不用再动脑了，哈哈。。
> > > 
> > > 
> > > 等我测试通过后发上来
> > 
> > 
> > 感谢！我用vnpy测试simnow账号也是63错误。
> 
> 仿真环境客户端验证通过了，下一步可以申请真实环境了


恭喜。我昨晚改的，对照你的代码是一模一样的，现在测试simnow还是63。还得等期货公司发码下来，这都申请第三天了。

**Comment by abao1900** [comment]
> > > > > > 和期货公司沟通了下，说是要用模拟账号进行仿真测试，难怪我用正式账号会报认证错误，继续等模拟账号下来再试
> > > > > 
> > > > > 
> > > > > 好的。如果方便的话麻烦把认证的代码也共享一下，这样我们其他人就不用再动脑了，哈哈。。
> > > > 
> > > > 
> > > > 等我测试通过后发上来
> > > 
> > > 
> > > 感谢！我用vnpy测试simnow账号也是63错误。
> > 
> > 
> > 仿真环境客户端验证通过了，下一步可以申请真实环境了
> 
> 恭喜。我昨晚改的，对照你的代码是一模一样的，现在测试simnow还是63。还得等期货公司发码下来，这都申请第三天了。

63那个错误  authcode申请了第二天才能生效  第一天都那样

**Comment by SafeCryptex** [comment]
> > > > > > > 和期货公司沟通了下，说是要用模拟账号进行仿真测试，难怪我用正式账号会报认证错误，继续等模拟账号下来再试
> > > > > > 
> > > > > > 
> > > > > > 好的。如果方便的话麻烦把认证的代码也共享一下，这样我们其他人就不用再动脑了，哈哈。。
> > > > > 
> > > > > 
> > > > > 等我测试通过后发上来
> > > > 
> > > > 
> > > > 感谢！我用vnpy测试simnow账号也是63错误。
> > > 
> > > 
> > > 仿真环境客户端验证通过了，下一步可以申请真实环境了
> > 
> > 
> > 恭喜。我昨晚改的，对照你的代码是一模一样的，现在测试simnow还是63。还得等期货公司发码下来，这都申请第三天了。
> 
> 63那个错误 authcode申请了第二天才能生效 第一天都那样


是的，谢谢提醒。

此issue的问题已解决，如有需要请参考上面的网盘链接。
再次感谢原创作者shizhuolin，以及提供编译版本的hanmin72 ，谢谢！

**Comment by dbsxdbsx** [comment]
请问下链接能更新下么，失效了
