### ISSUE TITLE
最新版本ubuntu下编译错误

### ISSUE THREAD

**Issue by hanmin72** [shizhuolin/PyCTP#16]
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/./src/stdafx.o build/temp.linux-x86_64-3.6/./src/PyCTP.o build/temp.linux-x86_64-3.6/./src/UserApiDataType.o build/temp.linux-x86_64-3.6/./src/UserApiStruct.o build/temp.linux-x86_64-3.6/./src/MdApi.o build/temp.linux-x86_64-3.6/./src/TraderApi.o -L./v6.3.15_20190220_api_tradeapi_se_linux64 -Wl,--enable-new-dtags,-R./ -lthostmduserapi_se -lthosttraderapi_se -lWinDataCollect -o build/lib.linux-x86_64-3.6/PyCTP.cpython-36m-x86_64-linux-gnu.so
/usr/bin/ld: 找不到 -lWinDataCollect
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-g++' failed with exit status 1
这是什么原因，DataCollect.h和libLinuxDataCollect.so都已经复制到/usr/local/lib和include目录了

**Comment by hanmin72** [comment]
已解决，修改setup.py即可

**Comment by SafeCryptex** [comment]
根据楼主hanmin72在另一议题的回复提示，我整理了一下需要修改的地方。

setup.py第19行至36行修改为：
`if platform.system() == 'Linux':
    optional['extra_compile_args'] = ['-std=c++11']
    optional['runtime_library_dirs'] = ['./']
    optional['include_dirs']=['./v6.3.15_20190220_api_tradeapi_se_linux64','v6.3.15_20190220_api_clientdatacollectdll_linux64']
    optional['library_dirs']=['./v6.3.15_20190220_api_tradeapi_se_linux64','v6.3.15_20190220_api_clientdatacollectdll_linux64']
#    depend_dynamics = ['libthostmduserapi.so', 'libthosttraderapi.so']
    argments = dict(name='PyCTP',
                sources=sources,
                language='c++',
                libraries=['thostmduserapi_se', 'thosttraderapi_se','LinuxDataCollect'],
                depends=depends)
if platform.system() == 'Windows':
    optional['include_dirs'] = ['./v6.3.15_20190220_tradeapi_se_windows','v6.3.15_20190220_clientdll_windows']
    optional['library_dirs'] = ['./v6.3.15_20190220_tradeapi_se_windows','v6.3.15_20190220_clientdll_windows']
    if '64 bit' in platform.python_compiler():
        optional['include_dirs'] = ['./v6.3.15_20190220_tradeapi64_se_windows','v6.3.15_20190220_clientdll64_windows']
        optional['library_dirs'] = ['./v6.3.15_20190220_tradeapi64_se_windows','v6.3.15_20190220_clientdll64_windows']
#    depend_dynamics = ['thostmduserapi.dll', 'thosttraderapi.dll']
    argments = dict(name='PyCTP',
                sources=sources,
                language='c++',
                libraries=['thostmduserapi_se', 'thosttraderapi_se','WinDataCollect'],
                depends=depends)`

APIToPyCTP.py第52、53行修改为：
codetree.update(structtrue('./v6.3.6_20160606_api_tradeapi_linux64/ThostFtdcUserApiDataType.h'))
codetree.update(structtrue('./v6.3.6_20160606_api_tradeapi_linux64/ThostFtdcUserApiStruct.h'))

目前在ubuntu+python3.5环境下编译成功，供参考。
![setup](https://user-images.githubusercontent.com/50958363/59742952-6eee1f00-92a1-11e9-8c1d-28b3a4229141.jpg)

**Comment by hanmin72** [comment]
Ubuntu下测试仿真账号，验证通过。
在PyCTP_Trader_API类里面添加2个函数
def Authenticate(self, BrokerID, UserID, AppID,AuthCode):
        """ 客户端请求认证"""
        reqAuthenticate = dict(BrokerID    = BrokerID
                            , UserID    = UserID
                            , UserProductInfo=AppID
                            , AuthCode  =AuthCode
                            , AppID  = AppID)
        self.__rsp_Authenticate = dict(event       = threading.Event()
                                , RequestID = self.__IncRequestID())
        ret = self.ReqAuthenticate(reqAuthenticate, self.__rsp_Authenticate['RequestID'])
        if ret == 0:
            self.__rsp_Authenticate['event'].clear()
            if self.__rsp_Authenticate['event'].wait(self.TIMEOUT):
                if self.__rsp_Authenticate['ErrorID'] == 0:
                    return 0
                else:
                    sys.stderr.write(str(self.__rsp_Authenticate['ErrorMsg'], encoding='gb2312'))
                return self.__rsp_Authenticate['ErrorID']
            else:
                return -4
        return ret

def OnRspAuthenticate(self,RspAuthenticate,RspInfo,RequestID, IsLast):
        """ 登录请求响应 """
        if RequestID == self.__rsp_Authenticate['RequestID'] and IsLast:
            self.__BrokerID = RspAuthenticate['BrokerID']
            self.__UserID = RspAuthenticate['UserID']
            self.__rsp_Authenticate.update(RspInfo)
            self.__rsp_Authenticate['event'].set()

修改__main__():

def __main__():
    import os
    import time
    BrokerID = b'8016'
    UserID = b''
    Password = b''
    ExchangeID = b'SHFE'
    InstrumentID = b'cu1910'
    AppID   = b''
    AuthCode    = b''
    print('终端信息:', PyCTP.CTP_GetSystemInfo())
    trader = PyCTP_Trader.CreateFtdcTraderApi(b'_tmp_t_')    
    #market = PyCTP_Market.CreateFtdcMdApi(b'_tmp_m_')    
    print('连接前置', trader.Connect(b'tcp://180.166.30.117:41209'))
    #print('连接前置', market.Connect(b'tcp://180.166.30.117:41214'))
    print('客户端认证', trader.Authenticate(BrokerID, UserID,AppID,AuthCode))
    print('账号登陆', trader.Login(BrokerID, UserID, Password))
