### ISSUE TITLE
新增6.3.8_2017-11-23支持

### ISSUE THREAD

**Issue by xiaoluffy** [shizhuolin/PyCTP#2]
请问能不能用新版本，并加入商品期权的支持。
http://www.sfit.com.cn/DocumentDown/api/6.3.8_20171123_traderapi.rar
谢谢！

**Comment by shizhuolin** [comment]
可以做到，下载最新版本ctp解压后替换老版本就行，替换后再重新编译。

**Comment by xiaoluffy** [comment]
Linux 64 + 3.6已经直接build通过了， 貌似新的函数已经加入了！
太牛了！

grep -R OnRspOptionSelfCloseInsert *
Binary file PyCTP.cpython-36m-x86_64-linux-gnu.so matches
